### ISSUE TITLE
[Bug] playerHead not working in DYNAMIC_PAGINATION

### ISSUE THREAD

**Issue by MrLouisDew** [Maxlego08/zMenu#107]
```
  teams:
    item:
      playerHead: "%parties_list_parties_by_members_%current%_leader_name%"
    type: DYNAMIC_PAGINATION
    start: 10
    end: 16
    slots:
      - 10-16
```

For example, the above configuration does not work. The playerHead turns into a default head (see screenshot) 
The playerHead feature does work as expected in normal buttons, but not in DYNAMIC_PAGINATION.

![Image](https://github.com/user-attachments/assets/9a61f0ae-e12a-4e92-b26e-38c71b67b2ca)
