### ISSUE TITLE
Actions de type inventory

### ISSUE THREAD

**Issue by 2robie** [Maxlego08/zMenu#109]
Rajouter par default que le plugin c'est zMenu.
```
  actions:
      - type: inventory
        plugin: zMenu
        inventory: divers
```
