### ISSUE TITLE
zMenu suggestions

### ISSUE THREAD

**Issue by zlAquiles** [Maxlego08/zMenu#12]
a suggestion for zMenu
Example: I run the command /tpa <player>, using that command will open a menu

Now what I want to do is open another menu with the same command (but not the same), the command would simply be /tpa
the first menu needs the player's name to open, but if he doesn't put a name, a different menu would be executed
in short, it would be 1 menu for the /tpa <player> command and another menu for the /tpa command

**Comment by Maxlego08** [comment]
Avaible with 1.0.0.8 !
```yml
commands:
  example1:
    command: openfiles
    inventory: example3
    arguments:
      - name,false,zmenu:example2
```
