### ISSUE TITLE
Suggestion \ Add a sudo option in the player_command

### ISSUE THREAD

**Issue by LegendsOfXania** [Maxlego08/zMenu#128]
Please add an option to sudo a player command. The configuration should look like this : 

```yml
actions:
  - type: player command
  commands:
    - "firstcommand"
    - "seconds commands %player%"
  command-in-chat: false
  sudo: boolean # false by default
```

Thanks you so much for this great plugin and have a nice evening.
