### ISSUE TITLE
[Suggestion] Argument support in /zmenu open command

### ISSUE THREAD

**Issue by paulreob** [Maxlego08/zMenu#13]
Sending the player a store menu with defined arguments, to be able to make a single template, this would save us a lot of time and from 40 menus to just one

Example: /zmenu open %player% {arg1} {arg2} {arg2}

```yaml
   show_item:
     material: itemsadder-souleaf:%zmenu_argument_name%
     ...
     click_commands:
     - '[console] iagive %player_name% souleaf:%zmenu_argument_name% 1 silent'
     - '[console] eco take %player% %zmenu_argument_price%'
```
