### ISSUE TITLE
[Suggestion] Add "ALL" for the "click_requirement"

### ISSUE THREAD

**Issue by NoltoxGit** [Maxlego08/zMenu#24]
Hello,
For the `click_requirement` requirement, would it be possible to set `ALL` instead of setting them all each time?

For example :
```yml
    click_requirement:
      clickslists:
        clicks:
        - ALL
```
