### ISSUE TITLE
[Suggestion] Add "delay" for the buttons actions

### ISSUE THREAD

**Issue by NoltoxGit** [Maxlego08/zMenu#25]
Hello,
Would it be possible to add a new type of action to the buttons: **delay** please? 

For example :
```yml
          success:
          - type: delay
            delay: 0.1      #Delay in seconds, so for this example is 0.1 seconds
          - type: console_command
            commands:
            - "quests:quests admin opengui category %player% codex-abeille"
```
