### ISSUE TITLE
[Suggestion] New features for commands.yml

### ISSUE THREAD

**Issue by KM-Owner** [Maxlego08/zMenu#26]
I would like to completely remove all GUI/Command plugins and move everything to the zMenu
But I still use the mycommand plugin because the zMenu - **commands.yml** is missing some functions

**1. Creating commands that execute other command to make command more simple for players:**
```
nether:
  command: /nether
  type: RUN_COMMAND
  runcmd:
  - '/warp nether'
  register: true
  permission-required: false
```

**2. Creating commands that send text to the player**
```
discord:
  command: /discord
  type: TEXT
  text:
  - ""
  - "                              $hex%#00b5e8%&lD$hex%#18bbec%&lI$hex%#2fc0f0%&lS$hex%#47c6f4%&lC$hex%#5ecbf7%&lO$hex%#76d1fb%&lR$hex%#8dd6ff%&lD"
  - "     &fPotrzebujesz pomocy lub chcesz być na bieżąco?"
  - "         &fDołącz na naszego discorda! $hex%#93FEFE%dc.krystalmc.pl"
  - ''
  register: true
  permission-required: false
```
