### ISSUE TITLE
[Feature request] add matrix for slots

### ISSUE THREAD

**Issue by DxrkCat** [Maxlego08/zMenu#39]
check title

**Comment by Maxlego08** [comment]
Example:
```yml
slot:
  - "xxxxxxxxx"
  -  "x-------x"
  -  "x-------x"
  -  "x-------x"
  -  "x-------x"
  -  "xxxxxxxxx"
```

**Comment by Maxlego08** [comment]
```yml
name: "&8Test"
size: 54
matrix:
  - "AAAAAAAAA"
  - "A       A"
  - "A   b   A"
  - "A   b   A"
  - "A  bbb  A"
  - "AAAAAAAAA"
items:
  A:
    item:
      material: DIAMOND
      name: "Letsgo"
  b:
    item:
      material: EMERALD
      name: "Letsgo"
```
its done !
