### ISSUE TITLE
[Suggestion] Target placeholder

### ISSUE THREAD

**Issue by NoltoxGit** [Maxlego08/zMenu#54]
Hello,
Add the posibility to get a placeholder for a specific player.
For a requirement it would be:
```yml
- type: placeholder
  placeholder: <placeholder>
  target: <player / placeholder with player name>
  value: <placeholder value>
  action: <placeholder action>
```

> _Suggested by `@saildrag` on the [GroupeZ Discord](https://discord.com/invite/AQETCvsw)._
