### ISSUE TITLE
[Suggestion] Add permission for new auto-complete feature

### ISSUE THREAD

**Issue by NoltoxGit** [Maxlego08/zMenu#66]
Hello,
Would it be possible to add a permission to display an auto-completion command?

```yml
commands:
  punish:
    command: punish
    permission: "admin.punish"
    aliases:
      - sanction
    inventory: example_punish
    arguments:
      - name: target
      - name: reason
        auto-completion:
          - cheat
          - chat
          - skin
          - other
        actions:
          - type: message
            messages:
              - "&7You will put a punishment to the player &f&n%target%&r &7with the reason&8: &f%reason%" 
          - type: permission_argument
            permissons:
              - "admin.punish.command"
```
