### ISSUE TITLE
[Suggestion] Add requirements for PlayerDatas

### ISSUE THREAD

**Issue by NoltoxGit** [Maxlego08/zMenu#69]
Hello,
Would it be possible to add a requirement with the player datas system ?
```yml
      requirements:
        - type: data
          key: "KEY"
          value: "VALUE"
```
And for the invert:
```yml
      requirements:
        - type: !data
          key: "KEY"
          value: "VALUE"
```
